import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from '@/app/providers/NextAuthProvider';
import LoginButton from "@components/auth/LoginButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          {/* Topnav */}
          <nav className="flex h-16 p-2 bg-teal-400 items-center">
            <LoginButton></LoginButton>
          </nav>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
